### ISSUE TITLE
plenty of broken links including feedback

### ISSUE THREAD

**Issue by nekromoff** [Libre-TrainSim/Libre-TrainSim#292]
This is a bug report for the website and the game. The feedback URL does not exist.

Also, plenty of links on the website point to 404 or even to the old repository address of the author.

Please, fix, it can be really dissuading from leaving feedback, moreover you won't be receiving any at all this way.

**Comment by HaSa1002** [comment]
Fixed in #298

**Comment by nekromoff** [comment]
this one still not working: https://www.libre-trainsim.de/contribute

**Comment by HaSa1002** [comment]
@nekromoff Where do you spotted the link?

**Comment by nekromoff** [comment]
In game (menu scene, top right): https://www.libre-trainsim.de/feedback
In game (menu scene, in the menu Create content): https://www.libre-trainsim.de/contribute

**Comment by HaSa1002** [comment]
All of these are fixed in 0.9.
